### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by kenborge** [Independer/angular-named-lazy-chunks-webpack-plugin#2]
It looks like the plugin doesn't work anymore with webpack 4 becuase of the changes they made to the chunk graph.

You get the following error 
```
Error: Chunk.blocks: Use ChunkGroup.getBlocks() instead
  at Chunk.get (.../node_modules/webpack/lib/Chunk.js:457:9)
    at AngularNamedLazyChunksWebpackPlugin.nameResolver (.../node_modules/angular-named-lazy-chunks-webpack-plugin/index.js:85:17)
```

**Comment by pglazkov** [comment]
Version 2.0.0 that adds Webpack 4 support has been published to NPM. Please give it a try.

**Comment by kenborge** [comment]
Seems to work great!
